title: 
description: >-
  Free Design Resources - Web Design Information - Search Engine Guides
baseurl: "" 
url: "https://www.roobenweb.com" 

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
