title: 
email: roobenweb@gmail.com
description: >-
  Hello! My name is Ruben Gutierrez I am a Website Designer in the 
  La Habra, California Area. 
baseurl: "" 
url: "https://www.roobenweb.com" 

# Build settings
theme: 
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
