title: Ruben Gutierrez | Website Designer
email: roobenweb@gmail.com
description: >-
  Website Designer - Free Design Resources - Web Design - Search Engine Tutorials
baseurl: "" 
url: "https://www.roobenweb.com" 

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
