# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 
email: roobenweb@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hello! My name is Ruben Gutierrez & I make websites.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://roobenweb.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: roobenweb
github_username:  roobenweb

# Build settings
theme: 
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
